[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "simtracer"
version = "0.3.0"
description = "Tools for inspecting Cerebras simulator CTF traces"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
dependencies = ["pyelftools", "tqdm"]
authors = [
    {name = "Tim Noack", email = "noack@esa.tu-darmstadt.de"},
]

[tool.setuptools]
py-modules = ["ctf", "callstack", "perfetto_pb", "simflame", "simtrace", "simperfetto"]

[project.scripts]
simflame = "simflame:main"
simtrace = "simtrace:main"
simperfetto = "simperfetto:main"
